"""I deleted all the tables

Revision ID: 09935206dd3a
Revises: 2cc75aae8c8b
Create Date: 2022-03-26 21:22:42.809637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09935206dd3a'
down_revision = '2cc75aae8c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
