"""I deleted all the tables

Revision ID: 1135d94bdab7
Revises: 34a091fb9d0b
Create Date: 2022-02-09 08:32:21.503968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1135d94bdab7'
down_revision = '34a091fb9d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
