"""I deleted all the tables

Revision ID: 1c5dea1b9253
Revises: 75614e5daa21
Create Date: 2022-01-17 23:59:50.746618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5dea1b9253'
down_revision = '75614e5daa21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
