"""I deleted all the tables

Revision ID: 28a9f3d8e255
Revises: 1135d94bdab7
Create Date: 2022-02-09 21:40:50.556292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a9f3d8e255'
down_revision = '1135d94bdab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
