"""I deleted all the tables

Revision ID: 2b50473cccaf
Revises: d5204721132b
Create Date: 2022-03-23 00:53:44.089888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b50473cccaf'
down_revision = 'd5204721132b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
