"""I deleted all the tables

Revision ID: 2cc75aae8c8b
Revises: fb92705caf09
Create Date: 2022-03-25 21:18:43.369796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc75aae8c8b'
down_revision = 'fb92705caf09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
