"""I deleted all the tables

Revision ID: 34420f393efc
Revises: e6fbfc3db926
Create Date: 2022-01-05 20:54:29.978908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34420f393efc'
down_revision = 'e6fbfc3db926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
