"""I deleted all the tables

Revision ID: 35d117a5ec77
Revises: 2b50473cccaf
Create Date: 2022-03-23 01:53:41.930199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d117a5ec77'
down_revision = '2b50473cccaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
