"""I deleted all the tables

Revision ID: 3b5cf848cc0c
Revises: 09935206dd3a
Create Date: 2022-03-27 02:58:34.800554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5cf848cc0c'
down_revision = '09935206dd3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
