"""I deleted all the tables

Revision ID: 40d55e18cf56
Revises: 6fa87601a0fe
Create Date: 2022-03-21 00:08:30.964571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d55e18cf56'
down_revision = '6fa87601a0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
