"""I deleted all the tables

Revision ID: 4875cc0b60b7
Revises: a06b0b0cd76a
Create Date: 2023-01-02 05:54:38.769167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4875cc0b60b7'
down_revision = 'a06b0b0cd76a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
