"""I deleted all the tables

Revision ID: 4b7470d47ff9
Revises: ca0b27ada40c
Create Date: 2021-12-23 18:38:12.267069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7470d47ff9'
down_revision = 'ca0b27ada40c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
