"""I deleted all the tables

Revision ID: 525ce6618334
Revises: ef982441633e
Create Date: 2022-03-04 18:00:39.304140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525ce6618334'
down_revision = 'ef982441633e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
