"""I deleted all the tables

Revision ID: 584a6c54df44
Revises: f1c5f56d6ef3
Create Date: 2021-12-22 20:02:55.466473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584a6c54df44'
down_revision = 'f1c5f56d6ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
