"""I deleted all the tables

Revision ID: 61611033831e
Revises: c7fe14d65cb1
Create Date: 2022-01-19 20:45:37.301918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61611033831e'
down_revision = 'c7fe14d65cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
