"""I deleted all the tables

Revision ID: 66c3de182898
Revises: 7437a6417c04
Create Date: 2021-12-22 19:08:03.300330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66c3de182898'
down_revision = '7437a6417c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'num_reviewed')
    op.drop_column('data', 'confidence')
    op.drop_column('data', 'users_reviewed')
    op.drop_column('project', 'is_iou')
    op.drop_column('project', 'threshold')
    op.drop_column('project', 'max_users')
    op.drop_column('segmentation', 'counted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segmentation', sa.Column('counted', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('max_users', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('threshold', mysql.FLOAT(), nullable=False))
    op.add_column('project', sa.Column('is_iou', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('data', sa.Column('users_reviewed', mysql.JSON(), nullable=False))
    op.add_column('data', sa.Column('confidence', mysql.FLOAT(), nullable=False))
    op.add_column('data', sa.Column('num_reviewed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
