"""I deleted all the tables

Revision ID: 67b29ddd74ef
Revises: a727f9be30cf
Create Date: 2022-02-04 01:53:49.526203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67b29ddd74ef'
down_revision = 'a727f9be30cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'confidence')
    op.drop_column('data', 'users_reviewed')
    op.drop_column('data', 'num_reviewed')
    op.drop_column('project', 'threshold')
    op.drop_column('project', 'max_users')
    op.drop_column('project', 'is_iou')
    op.drop_column('segmentation', 'counted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segmentation', sa.Column('counted', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('is_iou', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('max_users', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('threshold', mysql.FLOAT(), nullable=False))
    op.add_column('data', sa.Column('num_reviewed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('data', sa.Column('users_reviewed', mysql.JSON(), nullable=False))
    op.add_column('data', sa.Column('confidence', mysql.FLOAT(), nullable=False))
    # ### end Alembic commands ###
