"""I deleted all the tables

Revision ID: 6cb02cd8cda5
Revises: 9c468018604f
Create Date: 2023-01-11 04:50:35.213398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb02cd8cda5'
down_revision = '9c468018604f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
