"""I deleted all the tables

Revision ID: 7437a6417c04
Revises: 437ff5c9ce12
Create Date: 2021-12-20 21:31:22.470020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7437a6417c04'
down_revision = '437ff5c9ce12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
