"""I deleted all the tables

Revision ID: 75614e5daa21
Revises: 8eada2c0aa19
Create Date: 2022-01-17 10:03:16.810902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75614e5daa21'
down_revision = '8eada2c0aa19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
