"""I deleted all the tables

Revision ID: 82745e74a0f8
Revises: f508aaa254af
Create Date: 2022-03-11 06:48:02.749327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82745e74a0f8'
down_revision = 'f508aaa254af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
