"""I deleted all the tables

Revision ID: 836b6d03d88c
Revises: bd13d87a6a46
Create Date: 2022-02-23 20:17:19.414486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836b6d03d88c'
down_revision = 'bd13d87a6a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
