"""I deleted all the tables

Revision ID: 8b19913b1110
Revises: 4922a9762c22
Create Date: 2022-03-23 05:18:37.842546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b19913b1110'
down_revision = '4922a9762c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
