"""I deleted all the tables

Revision ID: 8eada2c0aa19
Revises: abeff48984f5
Create Date: 2022-01-17 06:53:49.256667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eada2c0aa19'
down_revision = 'abeff48984f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
