"""I deleted all the tables

Revision ID: 94c3d194538e
Revises: 6cb02cd8cda5
Create Date: 2023-01-11 04:57:56.194854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c3d194538e'
down_revision = '6cb02cd8cda5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
