"""I deleted all the tables

Revision ID: 97f5764433ec
Revises: 8405ddddc882
Create Date: 2022-03-20 23:26:02.192149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f5764433ec'
down_revision = '8405ddddc882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
