"""I deleted all the tables

Revision ID: 990428ecc2c3
Revises: 35d117a5ec77
Create Date: 2022-03-23 04:38:53.935757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990428ecc2c3'
down_revision = '35d117a5ec77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=100), nullable=False),
    sa.Column('is_marked_for_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('sampling_rate', sa.Integer(), nullable=False),
    sa.Column('clip_length', sa.Float(), nullable=False),
    sa.Column('confident_check', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
