"""I deleted all the tables

Revision ID: 9c468018604f
Revises: 4875cc0b60b7
Create Date: 2023-01-07 20:46:57.372079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c468018604f'
down_revision = '4875cc0b60b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
