"""I deleted all the tables

Revision ID: 9dc0029e7c8c
Revises: daff55000da8
Create Date: 2022-02-14 18:24:42.025722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc0029e7c8c'
down_revision = 'daff55000da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
