"""I deleted all the tables

Revision ID: 9df36c8de3d0
Revises: 49f8dd44eda4
Create Date: 2022-01-12 20:31:11.951210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df36c8de3d0'
down_revision = '49f8dd44eda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
