"""I deleted all the tables

Revision ID: a06b0b0cd76a
Revises: 0a9eb887e739
Create Date: 2023-01-02 05:05:28.034904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06b0b0cd76a'
down_revision = '0a9eb887e739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
