"""I deleted all the tables

Revision ID: a4e1d77a15ef
Revises: 8b19913b1110
Create Date: 2022-03-23 21:08:04.094110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e1d77a15ef'
down_revision = '8b19913b1110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
