"""I deleted all the tables

Revision ID: a727f9be30cf
Revises: d9cc5cce0455
Create Date: 2022-01-31 04:52:16.163196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a727f9be30cf'
down_revision = 'd9cc5cce0455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
