"""I deleted all the tables

Revision ID: abeff48984f5
Revises: dd58c1506eed
Create Date: 2022-01-17 06:37:21.571082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abeff48984f5'
down_revision = 'dd58c1506eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('confidence', sa.Float(), nullable=False))
    op.add_column('data', sa.Column('num_reviewed', sa.Integer(), nullable=False))
    op.add_column('data', sa.Column('users_reviewed', sa.JSON(), nullable=False))
    op.add_column('project', sa.Column('is_iou', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('max_users', sa.Integer(), nullable=False))
    op.add_column('project', sa.Column('threshold', sa.Float(), nullable=False))
    op.add_column('segmentation', sa.Column('counted', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segmentation', 'counted')
    op.drop_column('project', 'threshold')
    op.drop_column('project', 'max_users')
    op.drop_column('project', 'is_iou')
    op.drop_column('data', 'users_reviewed')
    op.drop_column('data', 'num_reviewed')
    op.drop_column('data', 'confidence')
    # ### end Alembic commands ###
