"""I deleted all the tables

Revision ID: b12d246b28e4
Revises: a4e1d77a15ef
Create Date: 2022-03-24 02:04:50.431005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b12d246b28e4'
down_revision = 'a4e1d77a15ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('type', table_name='label_type')
    op.drop_table('label_type')
    op.drop_table('label')
    op.drop_index('_label_id_value_uc', table_name='label_value')
    op.drop_table('label_value')
    op.drop_constraint('annotation_ibfk_1', 'annotation', type_='foreignkey')
    op.drop_column('annotation', 'label_value_id')
    op.add_column('segmentation', sa.Column('label', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segmentation', 'label')
    op.add_column('annotation', sa.Column('label_value_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('annotation_ibfk_1', 'annotation', 'label_value', ['label_value_id'], ['id'])
    op.create_table('label_value',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('label_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('value', mysql.VARCHAR(collation='utf8mb4_bin', length=200), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], name='label_value_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('_label_id_value_uc', 'label_value', ['label_id', 'value'], unique=True)
    op.create_table('label',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_bin', length=32), nullable=False),
    sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['label_type.id'], name='label_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('label_type',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_bin', length=32), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('type', 'label_type', ['type'], unique=True)
    # ### end Alembic commands ###
