"""I deleted all the tables

Revision ID: baa630d4b03e
Revises: 2fd8d68c9979
Create Date: 2021-12-20 20:00:14.382462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa630d4b03e'
down_revision = '2fd8d68c9979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('max_users', sa.Integer(), nullable=False))
    op.add_column('project', sa.Column('threshold', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'threshold')
    op.drop_column('project', 'max_users')
    # ### end Alembic commands ###
