"""I deleted all the tables

Revision ID: bd13d87a6a46
Revises: 9dc0029e7c8c
Create Date: 2022-02-16 08:21:28.887362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd13d87a6a46'
down_revision = '9dc0029e7c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
