"""I deleted all the tables

Revision ID: c158afb27cfc
Revises: 34420f393efc
Create Date: 2022-01-06 03:27:12.216704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c158afb27cfc'
down_revision = '34420f393efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
