"""I deleted all the tables

Revision ID: c7fe14d65cb1
Revises: 1c5dea1b9253
Create Date: 2022-01-19 08:35:58.081806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7fe14d65cb1'
down_revision = '1c5dea1b9253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
