"""I deleted all the tables

Revision ID: ca0b27ada40c
Revises: dd04daf6dc3e
Create Date: 2021-12-22 22:23:49.409497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0b27ada40c'
down_revision = 'dd04daf6dc3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
