"""I deleted all the tables

Revision ID: cd471dedde29
Revises: 66c3de182898
Create Date: 2021-12-22 19:10:55.257291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd471dedde29'
down_revision = '66c3de182898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
