"""I deleted all the tables

Revision ID: cf08b5cfbfe3
Revises: e44442e70dbc
Create Date: 2022-03-22 22:54:05.602019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf08b5cfbfe3'
down_revision = 'e44442e70dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
