"""I deleted all the tables

Revision ID: d7301d286d66
Revises: 61611033831e
Create Date: 2022-01-23 07:24:06.433748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7301d286d66'
down_revision = '61611033831e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
