"""I deleted all the tables

Revision ID: d9cc5cce0455
Revises: f03a7b769935
Create Date: 2022-01-31 00:47:04.314740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9cc5cce0455'
down_revision = 'f03a7b769935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
