"""I deleted all the tables

Revision ID: daff55000da8
Revises: c5ef4abe9be8
Create Date: 2022-02-14 06:46:53.856932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daff55000da8'
down_revision = 'c5ef4abe9be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
