"""I deleted all the tables

Revision ID: dd04daf6dc3e
Revises: 584a6c54df44
Create Date: 2021-12-22 20:45:57.497342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd04daf6dc3e'
down_revision = '584a6c54df44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
