"""I deleted all the tables

Revision ID: e44442e70dbc
Revises: 40d55e18cf56
Create Date: 2022-03-21 00:13:19.314694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44442e70dbc'
down_revision = '40d55e18cf56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
