"""I deleted all the tables

Revision ID: ecf2c7951ea4
Revises: baa630d4b03e
Create Date: 2021-12-20 20:03:03.403011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf2c7951ea4'
down_revision = 'baa630d4b03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
