"""I deleted all the tables

Revision ID: ef982441633e
Revises: 0ee184003795
Create Date: 2022-03-03 06:32:11.727423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef982441633e'
down_revision = '0ee184003795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
