"""I deleted all the tables

Revision ID: f03a7b769935
Revises: ad3db83417c5
Create Date: 2022-01-31 00:37:30.055197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03a7b769935'
down_revision = 'ad3db83417c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
