"""I deleted all the tables

Revision ID: f1c5f56d6ef3
Revises: cd471dedde29
Create Date: 2021-12-22 20:00:41.280810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c5f56d6ef3'
down_revision = 'cd471dedde29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
