"""I deleted all the tables

Revision ID: f33fb8987833
Revises: 82745e74a0f8
Create Date: 2022-03-19 00:13:19.442283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33fb8987833'
down_revision = '82745e74a0f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
