"""I deleted all the tables

Revision ID: f508aaa254af
Revises: 525ce6618334
Create Date: 2022-03-09 21:16:08.421077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f508aaa254af'
down_revision = '525ce6618334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
