"""I deleted all the tables

Revision ID: f6824495342f
Revises: c158afb27cfc
Create Date: 2022-01-07 05:50:33.020224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6824495342f'
down_revision = 'c158afb27cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
